// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hermite_normalization
NumericVector hermite_normalization(int N);
RcppExport SEXP _hermiter_hermite_normalization(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(hermite_normalization(N));
    return rcpp_result_gen;
END_RCPP
}
// hermite_function
NumericVector hermite_function(int N, NumericVector x, NumericVector normalization);
RcppExport SEXP _hermiter_hermite_function(SEXP NSEXP, SEXP xSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(hermite_function(N, x, normalization));
    return rcpp_result_gen;
END_RCPP
}
// hermite_integral_val
NumericVector hermite_integral_val(int N, NumericVector x, NumericMatrix hermite_function_mat);
RcppExport SEXP _hermiter_hermite_integral_val(SEXP NSEXP, SEXP xSEXP, SEXP hermite_function_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type hermite_function_mat(hermite_function_matSEXP);
    rcpp_result_gen = Rcpp::wrap(hermite_integral_val(N, x, hermite_function_mat));
    return rcpp_result_gen;
END_RCPP
}
// hermite_integral_val_quantile_adap
NumericVector hermite_integral_val_quantile_adap(int N, NumericVector x, NumericMatrix hermite_function_mat);
RcppExport SEXP _hermiter_hermite_integral_val_quantile_adap(SEXP NSEXP, SEXP xSEXP, SEXP hermite_function_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type hermite_function_mat(hermite_function_matSEXP);
    rcpp_result_gen = Rcpp::wrap(hermite_integral_val_quantile_adap(N, x, hermite_function_mat));
    return rcpp_result_gen;
END_RCPP
}
// standardizeInputs
NumericVector standardizeInputs(double x, double n_obs, double current_mean, double current_var);
RcppExport SEXP _hermiter_standardizeInputs(SEXP xSEXP, SEXP n_obsSEXP, SEXP current_meanSEXP, SEXP current_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< double >::type current_mean(current_meanSEXP);
    Rcpp::traits::input_parameter< double >::type current_var(current_varSEXP);
    rcpp_result_gen = Rcpp::wrap(standardizeInputs(x, n_obs, current_mean, current_var));
    return rcpp_result_gen;
END_RCPP
}
// standardizeInputsEW
NumericVector standardizeInputsEW(double x, double n_obs, double lambda, double current_mean, double current_var);
RcppExport SEXP _hermiter_standardizeInputsEW(SEXP xSEXP, SEXP n_obsSEXP, SEXP lambdaSEXP, SEXP current_meanSEXP, SEXP current_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type current_mean(current_meanSEXP);
    Rcpp::traits::input_parameter< double >::type current_var(current_varSEXP);
    rcpp_result_gen = Rcpp::wrap(standardizeInputsEW(x, n_obs, lambda, current_mean, current_var));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hermiter_hermite_normalization", (DL_FUNC) &_hermiter_hermite_normalization, 1},
    {"_hermiter_hermite_function", (DL_FUNC) &_hermiter_hermite_function, 3},
    {"_hermiter_hermite_integral_val", (DL_FUNC) &_hermiter_hermite_integral_val, 3},
    {"_hermiter_hermite_integral_val_quantile_adap", (DL_FUNC) &_hermiter_hermite_integral_val_quantile_adap, 3},
    {"_hermiter_standardizeInputs", (DL_FUNC) &_hermiter_standardizeInputs, 4},
    {"_hermiter_standardizeInputsEW", (DL_FUNC) &_hermiter_standardizeInputsEW, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hermiter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
